### ISSUE TITLE
Works but gives error in Fiji

### ISSUE THREAD

**Issue by lguerard** [imcf/python-imcflibs#12]
I just tested to use this in a script https://github.com/imcf/python-imcflibs/blob/2affd76b7228f228c4d0939ef95a96868c04eec1/src/imcflibs/imagej/bioformats.py#L136 

which exports the image but prints error in Fiji. We should investigate it and fix this if possible 

```log
java.io.FileNotFoundException: S:\Yuliya\frame_t_0.ets [001 405, 488, 561, 640]_cytoplasm_labels.tif (The process cannot access the file because it is being used by another process)
	at java.io.RandomAccessFile.open0(Native Method)
	at java.io.RandomAccessFile.open(RandomAccessFile.java:316)
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:243)
	at loci.common.NIOFileHandle.<init>(NIOFileHandle.java:130)
	at loci.common.NIOFileHandle.<init>(NIOFileHandle.java:151)
	at loci.common.NIOFileHandle.<init>(NIOFileHandle.java:165)
	at loci.common.Location.getHandle(Location.java:522)
	at loci.common.Location.getHandle(Location.java:462)
	at loci.common.Location.getHandle(Location.java:443)
	at loci.common.RandomAccessOutputStream.<init>(RandomAccessOutputStream.java:66)
	at loci.formats.FormatWriter.createOutputStream(FormatWriter.java:571)
	at loci.formats.out.TiffWriter.setupTiffSaver(TiffWriter.java:519)
	at loci.formats.out.TiffWriter.setId(TiffWriter.java:196)
	at loci.formats.FormatWriter.changeOutputFile(FormatWriter.java:123)
	at loci.plugins.out.Exporter.run(Exporter.java:815)
	at loci.plugins.LociExporter.run(LociExporter.java:75)
	at ij.plugin.filter.PlugInFilterRunner.processOneImage(PlugInFilterRunner.java:266)
	at ij.plugin.filter.PlugInFilterRunner.<init>(PlugInFilterRunner.java:114)
	at ij.IJ.runUserPlugIn(IJ.java:246)
	at ij.IJ.runPlugIn(IJ.java:210)
	at ij.Executer.runCommand(Executer.java:152)
	at ij.Executer.run(Executer.java:70)
	at ij.IJ.run(IJ.java:326)
	at ij.IJ.run(IJ.java:416)
	at sun.reflect.GeneratedMethodAccessor45.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:190)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:208)
	at org.python.core.PyObject.__call__(PyObject.java:494)
	at org.python.core.PyObject.__call__(PyObject.java:498)
	at imcflibs.imagej.bioformats$py.export$2(__pyclasspath__/imcflibs/imagej/bioformats.py:170)
	at imcflibs.imagej.bioformats$py.call_function(__pyclasspath__/imcflibs/imagej/bioformats.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:173)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:168)
	at org.python.core.PyFunction.__call__(PyFunction.java:437)
	at org.python.pycode._pyx4.f$0(H:\Projects\YuliyaKuchkovska\IMCFTODO-1198\cell_geometry.py:340)
	at org.python.pycode._pyx4.call_function(H:\Projects\YuliyaKuchkovska\IMCFTODO-1198\cell_geometry.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:173)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1687)
	at org.python.core.__builtin__.eval(__builtin__.java:497)
	at org.python.core.__builtin__.eval(__builtin__.java:501)
	at org.python.util.PythonInterpreter.eval(PythonInterpreter.java:255)
	at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:57)
	at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:31)
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at org.scijava.script.ScriptModule.run(ScriptModule.java:173)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:125)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:64)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:247)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

```

**Comment by ehrenfeu** [comment]
Could you verify this is an actual issue using a fresh VM that doesn't run anything but a single Fiji process?

The message suggests something else is having a filehandle open for the image:

`The process cannot access the file because it is being used by another process`

**Comment by rohangirishrao** [comment]
Just tested it on a fresh Fiji, exporting worked for me, couldn't reproduce any error. 

```
from imcflibs.imagej import bioformats
from ij import IJ
imp = IJ.getImage()
bioformats.export(imp, "export_test.tif", True)
```

**Comment by ehrenfeu** [comment]
Thanks a lot for testing Rohan! I'll wait for Laurent to comment as well as he was the original one coming across the issue.

**Comment by lguerard** [comment]
Tried it again and somehow it works now. I'll close this and reopen if I encounter the issue again.

Thanks both !
